### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by colinodell** [happyleavesaoc/python-myusps#1]
The `get_packages` method seems to fail with an error.  I believe this is occurring on international shipments where the "Shipped From:" field is empty:

![image](https://cloud.githubusercontent.com/assets/202034/22112082/b4e44526-de2f-11e6-8c20-206299cffae3.png)

Here's the stack trace from Home Assistant which uses this library:

```
17-01-19 10:05:57 homeassistant.components.sensor: Error while setting up platform usps
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_component.py", line 151, in _async_setup_platform
    entity_platform.add_entities, discovery_info
  File "uvloop/future.pyx", line 230, in __iter__ (uvloop/loop.c:110600)
  File "uvloop/future.pyx", line 432, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:113980)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108900)
  File "/usr/local/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/homeassistant/components/sensor/usps.py", line 51, in setup_platform
    add_devices([USPSSensor(session, config.get(CONF_UPDATE_INTERVAL))])
  File "/usr/src/app/homeassistant/components/sensor/usps.py", line 65, in __init__
    self.update()
  File "/usr/src/app/homeassistant/util/__init__.py", line 296, in wrapper
    result = method(*args, **kwargs)
  File "/usr/src/app/homeassistant/components/sensor/usps.py", line 81, in _update
    for package in myusps.get_packages(self._session):
  File "/usr/local/lib/python3.5/site-packages/myusps/__init__.py", line 98, in wrapped
    return function(*args)
  File "/usr/local/lib/python3.5/site-packages/myusps/__init__.py", line 127, in get_packages
    'shipped_from': row.xpath(SHIPPED_FROM_XPATH)[1].text.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by happyleavesaoc** [comment]
Thanks for the thorough report. Will get this fixed.

**Comment by happyleavesaoc** [comment]
Probably fixed @ https://github.com/happyleavesaoc/python-myusps/commit/f0c5ad50d309e996ce38397e191e978838d5abfe

It looks like your solution, basically.

**Comment by colinodell** [comment]
Perfect!  I look forward to seeing this make its way into HA soon :)
