### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'string'

### ISSUE THREAD

**Issue by colinodell** [happyleavesaoc/python-myusps#5]
```
17-03-02 22:20:44 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform ups
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_component.py", line 147, in _async_setup_platform
    entity_platform.schedule_add_entities, discovery_info
  File "uvloop/future.pyx", line 230, in __iter__ (uvloop/loop.c:110600)
  File "uvloop/future.pyx", line 432, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:113980)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108900)
  File "/usr/local/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/homeassistant/components/sensor/ups.py", line 49, in setup_platform
    cookie_path=cookie)
  File "/usr/local/lib/python3.5/site-packages/upsmychoice/__init__.py", line 156, in get_session
    _login(session, cookie_path)
  File "/usr/local/lib/python3.5/site-packages/upsmychoice/__init__.py", line 73, in _login
    error = parsed.find(ERROR_FIND_TAG, ERROR_FIND_ATTR).string
AttributeError: 'NoneType' object has no attribute 'string'
```

**Comment by colinodell** [comment]
Oops, I totally confused UPS and USPS.  Moving this to the other project...
